spring:
  profiles:
    active: @activatedProperties@
  resources:
    static-locations=classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  mvc:
    static-path-pattern=/static/**
  application:
    name: javademo-tyh-service-base
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB


  #  电子邮件
#  mail:
#    host: smtp.nbstar-alliance.com #发送邮件服务器
#    username: info@nbstar-alliance.com #发送邮件的邮箱地址
#    password: info123456.. #客户端授权码，不是邮箱密码,网易的是自己设置的
#    properties.mail.smtp.port: 465 #465或者994
#    from: info@nbstar-alliance.com # 发送邮件的地址，和上面username一致
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#  mvc:
#    static-path-pattern: /toHt/**
#设置自己启动的端口


